### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by aiueo49** [aiueo49/tanka_tukutta-#95]
お疲れ様です。
表題の件につきまして、レビューをお願いいたします。
***

## 各種情報
**サービス名**
短歌つくったー。
**サービスURL**
https://www.tankatukutta.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 会員登録機能
- [x] ログイン・ログアウト機能
- [x] 短歌作成機能
- [x] 短歌投稿機能
- [x] 短歌シェア機能
- [x] 短歌一覧閲覧機能
- [x] 短歌詳細機能
- [x] 短歌削除機能
- [ ] レスポンシブ機能

## READMEレビュー時から変更した機能
**作らなくなった機能**
- [ ] レスポンシブ機能

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/2319e16691e8b0ee45d65c0145a2b187.png)](https://gyazo.com/2319e16691e8b0ee45d65c0145a2b187)
[![Image from Gyazo](https://i.gyazo.com/13cd3578d8a42e0ccf298d3853e56b32.png)](https://gyazo.com/13cd3578d8a42e0ccf298d3853e56b32)
[![Image from Gyazo](https://i.gyazo.com/175f8f25bbacef0a1900eb16352de4e2.png)](https://gyazo.com/175f8f25bbacef0a1900eb16352de4e2)
[![Image from Gyazo](https://i.gyazo.com/8239cbf4dd68fb8122e3f4370839cc48.png)](https://gyazo.com/8239cbf4dd68fb8122e3f4370839cc48)
[![Image from Gyazo](https://i.gyazo.com/bb252bcb40d291ca077e61826ed27940.png)](https://gyazo.com/bb252bcb40d291ca077e61826ed27940)

**Comment by kenchasonakai** [comment]
LGTMです！
